source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'

# Database
gem 'mysql2', '~> 0.3.18'
gem 'activerecord-session_store', '~> 0.1.2'

# Presentation
gem 'sass-rails', '~> 5.0'
gem 'haml', '~> 4.0.7'
gem 'simple_form', '~> 3.2.1'
gem 'kaminari', '~> 0.16.3'
gem 'sitemap', '~> 0.3.3'
gem 'country_select', '~> 1.3.1'

# Javascript
gem 'jquery-rails', '~> 4.0.5'
gem 'uglifier', '>= 1.3.0'
gem 'tinymce-rails', '~> 4.3.3'
gem 'therubyracer', '~> 0.12.2'

# APIs
gem 'hominid'
gem 'mailchimp', '~> 0.0.9'

# Utilities
gem 'config', '~> 1.0.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'jbuilder', '~> 2.0'
gem 'nokogiri', '~> 1.6.7'
gem 'acts_as_list', '~> 0.7.2'
#gem 'paper_trail', '~> 4.0.1'
gem 'paperclip', '~> 4.3'
gem "net-ssh", "< 3.0"
#gem "mime-types", "~> 1.25"
#gem "treetop", "~> 1.4.15"
#gem "json", "~> 1.8.0"
#gem "mail", "~> 2.2.20"

# Authentication
gem 'cancan', '~> 1.6.10'
gem 'bcrypt', '~> 3.1.7'
gem 'bcrypt-ruby', '~> 3.1.5'
gem 'authlogic', '~> 3.4.6'

# Deployment
gem 'capistrano', '~> 2.15.7'
#gem 'capistrano-rails', '~> 1.1.5', group: :development

# Geocoding
gem 'geo_location', '~> 0.4.2'
gem "geokit", "~> 1.6.7"
gem "geokit-rails", "~> 2.1.0"
 # ugem 'debugger'
group :development, :test do
  # Call 'debugger' anywhere in the code to stop execution and get a debugger console
  # gem 'debugger'
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :production do
  gem 'passenger', '~> 5.0.23'
end

