editor_selector: tinymce
content_css: "/stylesheets/tiny_mce.css"
browsers:
  - msie
  - gecko
  - safari
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_resizing: true
theme_advanced_resize_horizontal: false
theme_advanced_blockformats:
  - h2
  - h3
theme_advanced_buttons1:
  - formatselect
  - bold
  - italic
  - sup
  - sub
  - separator
  - link
  - unlink
  - image
  - table
  - hr
  - separator
  - bullist
  - numlist
  - separator
  - pastetext
  - code
theme_advanced_buttons2: []
theme_advanced_buttons3: []
cleanup_on_startup: true
verify_html: false
convert_urls: false
invalid_elements:
  - object
  - embed
  - script
  - span
  - div
  - font
  - style
plugins:
  - paste
  - table
  - image
  - link
  - fullscreen
