# paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr
# paypal_email: robert_1303911699_biz@overdrivedesign.com
# paypal_cert_id: DWNUL4MYNPLC4
paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr
paypal_email: ashishbhai123-facilitator@mailinator.com
paypal_cert_id: GGUDY8N4AFFFTF2Z
#paypal_email: robert-facilitator@overdrivedesign.com
